import { MantineProvider } from "@mantine/core";
import { createElement } from "react";
import { renderToStaticMarkup } from "react-dom/server";
import { describe, expect, it, vi } from "vitest";

vi.mock("react-i18next", () => ({
  useTranslation: () => ({
    t: (key: string) => key,
  }),
}));
vi.mock("./recognition-log", () => ({
  RecognitionLog: () => null,
}));
// The icon modules are generated by the Vite plugin and do not exist on disk
// in the unit-test module graph.
// @ts-expect-error Vitest supports virtual mocks at runtime.
vi.mock("~icons/material-symbols/volume-off", () => ({ default: () => null }), {
  virtual: true,
});
// @ts-expect-error Vitest supports virtual mocks at runtime.
vi.mock("~icons/material-symbols/volume-up", () => ({ default: () => null }), {
  virtual: true,
});

import { activeSttProfiles, SttProfileVolumeRow } from "./runtime-panel";
import type { SttProfileConfig } from "../lib/types";

const profile = (overrides: Partial<SttProfileConfig> = {}) =>
  ({
    id: "profile-blue",
    name: "Blue microphone",
    enabled: true,
    display_color: "blue",
    input: {
      device_host: null,
      device_id: "device-1",
      device_name: "Microphone",
      channel_index: 0,
      volume_percent: 72,
      muted: false,
    },
    ...overrides,
  }) as SttProfileConfig;

describe("runtime STT profile volume row", () => {
  it("renders the profile color marker and controls in name, mute, slider, meter order", () => {
    const markup = renderToStaticMarkup(
      createElement(
        MantineProvider,
        null,
        createElement(SttProfileVolumeRow, {
          profile: profile(),
          displayName: "Blue microphone",
          level: { inputLevel: 0.2, inputLevelBeforeGain: 0.2 },
          onSetVolume: vi.fn(),
          onToggleMute: vi.fn(),
        }),
      ),
    );

    expect(markup).toContain('data-stt-profile-color="blue"');
    expect(markup).toContain("background-color:var(--mantine-color-blue-6)");

    const markerPosition = markup.indexOf('data-stt-profile-color="blue"');
    const namePosition = markup.indexOf("Blue microphone");
    const mutePosition = markup.indexOf(
      'aria-label="Blue microphone: sttProfiles.mute"',
    );
    const sliderPosition = markup.indexOf(
      'aria-label="Blue microphone: sttProfiles.volumeLabel"',
    );
    const meterPosition = markup.indexOf(
      'aria-label="Blue microphone: sttProfiles.inputLevel"',
    );

    expect(markerPosition).toBeGreaterThan(-1);
    expect(markerPosition).toBeLessThan(namePosition);
    expect(namePosition).toBeGreaterThan(-1);
    expect(mutePosition).toBeGreaterThan(namePosition);
    expect(sliderPosition).toBeGreaterThan(mutePosition);
    expect(meterPosition).toBeGreaterThan(sliderPosition);
  });

  it("keeps disabled STT profiles out of the runtime controls", () => {
    const active = profile();
    const disabled = profile({ id: "profile-disabled", enabled: false });

    expect(activeSttProfiles([active, disabled])).toEqual([active]);
  });
});
