import { MantineProvider } from "@mantine/core";
import { createElement } from "react";
import { renderToStaticMarkup } from "react-dom/server";
import { describe, expect, it, vi } from "vitest";

vi.mock("react-i18next", () => ({
  useTranslation: () => ({
    t: (key: string, values?: { name?: string }) =>
      values?.name ? `${key}:${values.name}` : key,
  }),
}));

// The icon modules are generated by the Vite plugin and do not exist on disk
// in the unit-test module graph.
vi.mock(
  "~icons/material-symbols/add",
  () => ({ default: () => null }),
  // @ts-expect-error Vitest supports virtual mocks at runtime.
  { virtual: true },
);
vi.mock(
  "~icons/material-symbols/auto-fix-high",
  () => ({ default: () => null }),
  // @ts-expect-error Vitest supports virtual mocks at runtime.
  { virtual: true },
);
vi.mock(
  "~icons/material-symbols/content-cut",
  () => ({ default: () => null }),
  // @ts-expect-error Vitest supports virtual mocks at runtime.
  { virtual: true },
);
vi.mock(
  "~icons/material-symbols/delete",
  () => ({ default: () => null }),
  // @ts-expect-error Vitest supports virtual mocks at runtime.
  { virtual: true },
);
vi.mock(
  "~icons/material-symbols/description",
  () => ({ default: () => null }),
  // @ts-expect-error Vitest supports virtual mocks at runtime.
  { virtual: true },
);
vi.mock(
  "~icons/material-symbols/download",
  () => ({ default: () => null }),
  // @ts-expect-error Vitest supports virtual mocks at runtime.
  { virtual: true },
);
vi.mock(
  "~icons/material-symbols/keyboard-arrow-down",
  () => ({ default: () => null }),
  // @ts-expect-error Vitest supports virtual mocks at runtime.
  { virtual: true },
);
vi.mock(
  "~icons/material-symbols/keyboard-arrow-up",
  () => ({ default: () => null }),
  // @ts-expect-error Vitest supports virtual mocks at runtime.
  { virtual: true },
);
vi.mock(
  "~icons/material-symbols/mic",
  () => ({ default: () => null }),
  // @ts-expect-error Vitest supports virtual mocks at runtime.
  { virtual: true },
);
vi.mock(
  "~icons/material-symbols/mic-noise-cancel-high",
  () => ({ default: () => null }),
  // @ts-expect-error Vitest supports virtual mocks at runtime.
  { virtual: true },
);
vi.mock(
  "~icons/material-symbols/refresh",
  () => ({ default: () => null }),
  // @ts-expect-error Vitest supports virtual mocks at runtime.
  { virtual: true },
);
vi.mock(
  "~icons/material-symbols/settings-ethernet",
  () => ({ default: () => null }),
  // @ts-expect-error Vitest supports virtual mocks at runtime.
  { virtual: true },
);
vi.mock(
  "~icons/material-symbols/speech-to-text",
  () => ({ default: () => null }),
  // @ts-expect-error Vitest supports virtual mocks at runtime.
  { virtual: true },
);
vi.mock(
  "~icons/material-symbols/translate",
  () => ({ default: () => null }),
  // @ts-expect-error Vitest supports virtual mocks at runtime.
  { virtual: true },
);
vi.mock(
  "~icons/material-symbols/tune",
  () => ({ default: () => null }),
  // @ts-expect-error Vitest supports virtual mocks at runtime.
  { virtual: true },
);
vi.mock(
  "~icons/material-symbols/voice-selection",
  () => ({ default: () => null }),
  // @ts-expect-error Vitest supports virtual mocks at runtime.
  { virtual: true },
);
vi.mock(
  "~icons/material-symbols/volume-off",
  () => ({ default: () => null }),
  // @ts-expect-error Vitest supports virtual mocks at runtime.
  { virtual: true },
);
vi.mock(
  "~icons/material-symbols/volume-up",
  () => ({ default: () => null }),
  // @ts-expect-error Vitest supports virtual mocks at runtime.
  { virtual: true },
);

import type { ParapperConfig, SttProfileConfig } from "../lib/types";
import { AsrSettings } from "./settings/asr-settings";
import { ConnectionSettings } from "./settings/connection-settings";
import { ExternalAppSettings } from "./settings/external-app-settings";
import {
  SttProfileDeleteConfirmationModal,
  SttProfileList,
} from "./settings-panel";

describe("STT connection profile list", () => {
  it("places each profile's activation checkbox and delete control after its selector, keeps the final active profile enabled, and puts add below the list", () => {
    const markup = renderToStaticMarkup(
      createElement(
        MantineProvider,
        null,
        createElement(SttProfileList, {
          profiles: [
            {
              id: "alice",
              label: "Alice",
              color: "blue",
              enabled: false,
              selected: false,
            },
            {
              id: "bob",
              label: "Bob",
              color: "green",
              enabled: true,
              selected: true,
            },
          ],
          disabled: false,
          onChange: vi.fn(),
          onEnabledChange: vi.fn(),
          onDelete: vi.fn(),
          onAdd: vi.fn(),
        }),
      ),
    );

    const aliceName = markup.indexOf("Alice");
    const aliceCheckbox = markup.indexOf(
      'aria-label="sttProfiles.enabledFor:Alice"',
    );
    const aliceDelete = markup.indexOf(
      'aria-label="sttProfiles.deleteFor:Alice"',
    );
    const bobName = markup.indexOf("Bob");
    const bobCheckbox = markup.indexOf(
      'aria-label="sttProfiles.enabledFor:Bob"',
    );
    const bobDelete = markup.indexOf('aria-label="sttProfiles.deleteFor:Bob"');
    const add = markup.lastIndexOf("sttProfiles.add");

    expect(aliceName).toBeGreaterThan(-1);
    expect(aliceCheckbox).toBeGreaterThan(aliceName);
    expect(aliceDelete).toBeGreaterThan(aliceCheckbox);
    expect(bobName).toBeGreaterThan(aliceDelete);
    expect(bobCheckbox).toBeGreaterThan(bobName);
    expect(bobDelete).toBeGreaterThan(bobCheckbox);
    expect(add).toBeGreaterThan(bobDelete);

    const bobCheckboxTag = markup.slice(
      markup.lastIndexOf("<input", bobCheckbox),
      markup.indexOf(">", bobCheckbox) + 1,
    );
    expect(bobCheckboxTag).toContain("disabled");
    expect(bobCheckboxTag).toContain("checked");
    expect(bobCheckboxTag).toContain("opacity:1");
    expect(markup).toContain(
      "--checkbox-color:var(--mantine-color-blue-filled)",
    );
    expect(markup).not.toContain("sttProfiles.enabled</label>");
  });

  it("shows the requested profile name in the delete confirmation without deleting before confirmation", () => {
    const onConfirm = vi.fn();
    const markup = renderToStaticMarkup(
      createElement(
        MantineProvider,
        null,
        createElement(SttProfileDeleteConfirmationModal, {
          profile: {
            id: "custom-source-id",
            name: "custom-source-id",
          } as SttProfileConfig,
          disabled: false,
          withinPortal: false,
          onCancel: vi.fn(),
          onConfirm,
        }),
      ),
    );

    expect(markup).toContain("sttProfiles.deleteConfirmationTitle");
    expect(markup).toContain(
      "sttProfiles.deleteConfirmationBody:custom-source-id",
    );
    expect(onConfirm).not.toHaveBeenCalled();
  });

  it("keeps the selected display color swatch outlined instead of filling its action icon", () => {
    const profile = {
      id: "alice",
      name: "Alice",
      neo_http_enabled: false,
      developer_http_enabled: true,
      display_color: "green",
      input: {
        device_host: null,
        device_id: null,
        device_name: null,
        channel_index: 0,
        volume_percent: 100,
        muted: false,
      },
    } as SttProfileConfig;
    const markup = renderToStaticMarkup(
      createElement(
        MantineProvider,
        null,
        createElement(ConnectionSettings, {
          input: profile.input,
          profiles: [profile],
          selectedProfileId: profile.id,
          profile,
          onUpdateProfile: vi.fn(),
          inputAudioDevices: [],
          runtimeLocked: false,
          localAudioDevicesAvailable: true,
          refreshingAudioDevices: false,
          onRefreshAudioDevices: vi.fn(),
          onRequestLoopbackPermission: vi.fn(async () => undefined),
          onChange: vi.fn(),
        }),
      ),
    );

    expect(markup).toContain('role="radio"');
    expect(markup).toContain('aria-checked="true"');
    expect(markup).toContain("background-color:transparent");
    expect(markup).toContain("border:2px solid var(--mantine-color-text)");
  });

  it("keeps device refresh as a dedicated button and omits the channel-count hint", () => {
    const profile = {
      id: "alice",
      name: "Alice",
      developer_http_enabled: true,
      display_color: "green",
      input: {
        device_host: "wasapi",
        device_id: "microphone",
        device_name: "Microphone",
        channel_index: 0,
        volume_percent: 100,
        muted: false,
      },
    } as SttProfileConfig;
    const markup = renderToStaticMarkup(
      createElement(
        MantineProvider,
        null,
        createElement(ConnectionSettings, {
          input: profile.input,
          profiles: [profile],
          selectedProfileId: profile.id,
          profile,
          onUpdateProfile: vi.fn(),
          inputAudioDevices: [
            {
              id: "microphone",
              host: "wasapi",
              display_name: "Microphone",
              channels: 2,
              sample_rate: 48_000,
            },
          ],
          runtimeLocked: false,
          localAudioDevicesAvailable: true,
          refreshingAudioDevices: false,
          onRefreshAudioDevices: vi.fn(),
          onRequestLoopbackPermission: vi.fn(async () => undefined),
          onChange: vi.fn(),
        }),
      ),
    );

    expect(markup).toContain(
      'aria-label="settings.audioDevice.refreshAriaLabel"',
    );
    expect(markup).toContain("sttProfiles.developerHttpEnabled");
    expect(markup).toContain("sttProfiles.neoHttpEnabled");
    expect(markup).toContain("checked");
    expect(markup).toContain("settings.inputAudioDevice.channelLabel");
    expect(markup.indexOf("sttProfiles.developerHttpEnabled")).toBeGreaterThan(
      markup.indexOf("settings.inputAudioDevice.channelLabel"),
    );
    expect(markup.indexOf("sttProfiles.neoHttpEnabled")).toBeGreaterThan(
      markup.indexOf("settings.inputAudioDevice.channelLabel"),
    );
    expect(markup).not.toContain("settings.inputAudioDevice.channelHint");
  });

  it("lists every STT profile directly below the Developer HTTP destination URL", () => {
    const profiles = [
      {
        id: "alice",
        name: "Alice",
        display_color: "green",
        neo_http_enabled: false,
        developer_http_enabled: true,
      },
      {
        id: "bob",
        name: "Bob",
        display_color: "blue",
        neo_http_enabled: true,
        developer_http_enabled: false,
      },
    ] as SttProfileConfig[];
    const markup = renderToStaticMarkup(
      createElement(
        MantineProvider,
        null,
        createElement(ExternalAppSettings, {
          config: {
            neo_http_enabled: true,
            neo_http_port: 15520,
            ync_plugin_port: 8080,
            vrc_osc_micmute: false,
            streaming_recognition_enabled: true,
            developer_connection_mode: "http",
            developer_http_url: "http://127.0.0.1:18081/",
          } as ParapperConfig,
          sttProfiles: profiles,
          runtimeLocked: false,
          nativeConnectionsAvailable: true,
          onFindNeoPort: vi.fn(async () => null),
          onFindYncPluginPort: vi.fn(async () => null),
          onSetDeveloperConnectionEnabled: vi.fn(),
          onSetSttProfileNeoHttpEnabled: vi.fn(),
          onSetSttProfileDeveloperHttpEnabled: vi.fn(),
          onUpdateConfig: vi.fn(),
        }),
      ),
    );
    const url = markup.indexOf("connectionSettings.httpUrl");
    const list = markup.indexOf("connectionSettings.httpProfiles");
    const alice = markup.indexOf("sttProfiles.developerHttpEnabledFor:Alice");
    const bob = markup.indexOf("sttProfiles.developerHttpEnabledFor:Bob");
    const payload = markup.indexOf("connectionSettings.httpPayloadExample");

    expect(url).toBeGreaterThanOrEqual(0);
    expect(list).toBeGreaterThan(url);
    expect(alice).toBeGreaterThan(list);
    expect(bob).toBeGreaterThan(alice);
    expect(payload).toBeGreaterThan(bob);
    const aliceTag = markup.slice(
      markup.lastIndexOf("<input", alice),
      markup.indexOf(">", alice) + 1,
    );
    const bobTag = markup.slice(
      markup.lastIndexOf("<input", bob),
      markup.indexOf(">", bob) + 1,
    );
    expect(aliceTag).toContain("checked");
    expect(bobTag).not.toContain("checked");
    const aliceColor = markup.indexOf("var(--mantine-color-green-6)", alice);
    const aliceVisibleName = markup.indexOf(">Alice<", alice);
    const bobColor = markup.indexOf("var(--mantine-color-blue-6)", bob);
    const bobVisibleName = markup.indexOf(">Bob<", bob);
    expect(aliceColor).toBeGreaterThan(alice);
    expect(aliceVisibleName).toBeGreaterThan(aliceColor);
    expect(bobColor).toBeGreaterThan(bob);
    expect(bobVisibleName).toBeGreaterThan(bobColor);

    const neoPort = markup.indexOf("settings.neoHttpPort.label");
    const neoList = markup.indexOf("connectionSettings.neoProfiles");
    const neoAlice = markup.indexOf("sttProfiles.neoHttpEnabledFor:Alice");
    const neoBob = markup.indexOf("sttProfiles.neoHttpEnabledFor:Bob");
    expect(neoList).toBeGreaterThan(neoPort);
    expect(neoAlice).toBeGreaterThan(neoList);
    expect(neoBob).toBeGreaterThan(neoAlice);
    const neoAliceTag = markup.slice(
      markup.lastIndexOf("<input", neoAlice),
      markup.indexOf(">", neoAlice) + 1,
    );
    const neoBobTag = markup.slice(
      markup.lastIndexOf("<input", neoBob),
      markup.indexOf(">", neoBob) + 1,
    );
    expect(neoAliceTag).not.toContain("checked");
    expect(neoBobTag).toContain("checked");
  });

  it("keeps profile row dimensions stable when selection changes", () => {
    const markup = renderToStaticMarkup(
      createElement(
        MantineProvider,
        null,
        createElement(SttProfileList, {
          profiles: [
            {
              id: "selected",
              label: "Selected",
              color: "blue",
              enabled: true,
              selected: true,
            },
            {
              id: "unselected",
              label: "Unselected",
              color: "green",
              enabled: true,
              selected: false,
            },
          ],
          disabled: false,
          onChange: vi.fn(),
          onEnabledChange: vi.fn(),
          onDelete: vi.fn(),
          onAdd: vi.fn(),
        }),
      ),
    );

    expect(markup).not.toContain("border:2px solid");
    expect(markup).toContain("border:1px solid var(--mantine-color-blue-6)");
    expect(markup).toContain(
      "border:1px solid var(--mantine-color-default-border)",
    );
  });

  it("shows ASR controls in the workflow order from models through hotword management", () => {
    const config = {
      asr_model: "reazonspeech_k2_v2",
      interim_asr_model: null,
      asr_precision: "int8-fp32",
      asr_num_threads: 4,
      asr_mode: "fast",
      asr_hotwords_enabled: false,
      asr_hotwords: [],
      asr_normalize_input_audio: true,
      multilingual_asr_enabled: false,
      enabled_asr_models: ["reazonspeech_k2_v2"],
    } as unknown as ParapperConfig;
    const markup = renderToStaticMarkup(
      createElement(
        MantineProvider,
        null,
        createElement(AsrSettings, {
          config,
          runtimeLocked: false,
          onUpdateConfig: vi.fn(),
          onApplyAsrModel: vi.fn(),
          onSuggestHotwordReadings: vi.fn(async () => []),
        }),
      ),
    );
    const labels = [
      "settings.asrModel.label",
      "settings.interimAsrModel.label",
      "settings.asrMode.label",
      "settings.asrPrecision.label",
      "settings.asrThreads.label",
      "settings.hotwords.enable",
      "settings.hotwords.manage",
    ];
    const positions = labels.map((label) => markup.indexOf(label));

    expect(positions.every((position) => position >= 0)).toBe(true);
    expect(positions).toEqual([...positions].sort((a, b) => a - b));
  });
});
