use std::path::Path;

use anyhow::Result;

use super::LocalTtsVoice;
#[cfg(feature = "tts-supertonic-ort")]
use super::SupertonicOnnxTtsEngine;

/// Audio generated by a local TTS model before host-specific playback.
pub struct SynthesizedTtsAudio {
    pub samples: Vec<f32>,
    pub sample_rate: i32,
}

/// Model-owned local TTS runtime.
///
/// The concrete Supertonic sessions and mutable speaker style stay in this
/// crate. Hosts provide a resolved model directory and own scheduling,
/// playback devices, and application events.
pub struct LocalTtsEngine {
    inner: LocalTtsEngineKind,
}

enum LocalTtsEngineKind {
    #[cfg(feature = "tts-supertonic-ort")]
    Supertonic(Box<SupertonicOnnxTtsEngine>),
}

impl LocalTtsEngine {
    /// Loads the selected voice from an already-resolved model directory.
    ///
    /// # Errors
    ///
    /// Returns an error when required model assets are missing or a native
    /// inference session cannot be constructed.
    pub fn load(model_dir: &Path, voice: LocalTtsVoice, num_threads: i32) -> Result<Self> {
        let _ = num_threads;
        #[cfg(feature = "tts-supertonic-ort")]
        return Ok(Self {
            inner: LocalTtsEngineKind::Supertonic(Box::new(SupertonicOnnxTtsEngine::new(
                model_dir,
                None,
                voice
                    .supported_language_codes()
                    .ok_or_else(|| anyhow::anyhow!("TTS languages are missing for {voice:?}"))?,
            )?)),
        });
        #[cfg(not(feature = "tts-supertonic-ort"))]
        anyhow::bail!("Supertonic TTS support is not enabled for voice {voice:?}")
    }

    /// Synthesizes one utterance while preserving model-specific mutable state.
    ///
    /// # Errors
    ///
    /// Returns an error when text preprocessing or model inference fails.
    pub fn synthesize(
        &mut self,
        text: &str,
        speaker_id: Option<i32>,
        language: Option<&str>,
    ) -> Result<SynthesizedTtsAudio> {
        #[cfg(not(feature = "tts-supertonic-ort"))]
        let _ = speaker_id;
        match &mut self.inner {
            #[cfg(feature = "tts-supertonic-ort")]
            LocalTtsEngineKind::Supertonic(engine) => Ok(SynthesizedTtsAudio {
                samples: engine.synthesize(text, speaker_id, language)?,
                sample_rate: engine.sample_rate,
            }),
        }
    }
}
